# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GEditorUI(object):
    def setupUi(self, GEditorUI):
        GEditorUI.setObjectName("GEditorUI")
        GEditorUI.resize(620, 770)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GEditorUI.sizePolicy().hasHeightForWidth())
        GEditorUI.setSizePolicy(sizePolicy)
        GEditorUI.setMinimumSize(QtCore.QSize(620, 680))
        GEditorUI.setMaximumSize(QtCore.QSize(620, 790))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GEditorUI.setWindowIcon(icon)
        GEditorUI.setStyleSheet("QPushButton{\n"
"color:#ffffff;\n"
"border:1px solid white;\n"
"}\n"
"#ccBox, #codecBox, #cropBox, #extractBox, #inputBox, #mergeBox, #outputBox, #speedBox {\n"
"border:1px solid rgb(100,100,100);\n"
"}\n"
"QLabel{\n"
"color:#ffffff;\n"
"}\n"
"QGroupBox{\n"
"color:#ffffff;\n"
"}\n"
"QLineEdit{\n"
"color:white;\n"
"border:1px solid rgb(100,100,100);\n"
"}\n"
"#vCodecTabs {\n"
"    border: 1px solid rgb(100,100,100);\n"
"}\n"
"QMessageBox {\n"
"background-color:#000;\n"
"color:#fff;}\n"
"QProgressBar{\n"
"color:#fff;\n"
"border:1px solid #fff;\n"
"}\n"
"QProgressBar::chunk {\n"
"background-color:#fff;\n"
"}")
        self.editMenu = QtWidgets.QStackedWidget(GEditorUI)
        self.editMenu.setEnabled(True)
        self.editMenu.setGeometry(QtCore.QRect(0, 0, 620, 900))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMenu.sizePolicy().hasHeightForWidth())
        self.editMenu.setSizePolicy(sizePolicy)
        self.editMenu.setMinimumSize(QtCore.QSize(620, 780))
        self.editMenu.setStyleSheet("QWidget{\n"
"background-color:#000;\n"
"font-family:century gothic;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#ffffff;\n"
"color:#000000;\n"
"border:1px solid black;\n"
"}")
        self.editMenu.setObjectName("editMenu")
        self.mainMenu = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenu.sizePolicy().hasHeightForWidth())
        self.mainMenu.setSizePolicy(sizePolicy)
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_text = QtWidgets.QLabel(self.mainMenu)
        self.welcome_text.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.welcome_text.setFont(font)
        self.welcome_text.setStyleSheet("color:#FFFFFF;\n"
"padding-bottom:20px;")
        self.welcome_text.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_text.setObjectName("welcome_text")
        self.verticalLayout.addWidget(self.welcome_text, 0, QtCore.Qt.AlignBottom)
        self.logo_menu = QtWidgets.QLabel(self.mainMenu)
        self.logo_menu.setStyleSheet("background-image:url(logo.png)")
        self.logo_menu.setText("")
        self.logo_menu.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_menu.setObjectName("logo_menu")
        self.verticalLayout.addWidget(self.logo_menu, 0, QtCore.Qt.AlignVCenter)
        self.button_menu_next = QtWidgets.QPushButton(self.mainMenu)
        self.button_menu_next.setMinimumSize(QtCore.QSize(50, 25))
        self.button_menu_next.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.button_menu_next.setFont(font)
        self.button_menu_next.setStyleSheet("")
        self.button_menu_next.setFlat(False)
        self.button_menu_next.setObjectName("button_menu_next")
        self.verticalLayout.addWidget(self.button_menu_next, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.editMenu.addWidget(self.mainMenu)
        self.funcSelect = QtWidgets.QWidget()
        self.funcSelect.setStyleSheet("")
        self.funcSelect.setObjectName("funcSelect")
        self.inputBox = QtWidgets.QGroupBox(self.funcSelect)
        self.inputBox.setGeometry(QtCore.QRect(20, 10, 581, 71))
        self.inputBox.setMinimumSize(QtCore.QSize(581, 71))
        self.inputBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.inputBox.setTitle("")
        self.inputBox.setObjectName("inputBox")
        self.inputText = QtWidgets.QLabel(self.inputBox)
        self.inputText.setGeometry(QtCore.QRect(10, 13, 47, 13))
        self.inputText.setObjectName("inputText")
        self.inputPath = QtWidgets.QLineEdit(self.inputBox)
        self.inputPath.setGeometry(QtCore.QRect(90, 11, 371, 20))
        self.inputPath.setObjectName("inputPath")
        self.inputBrowse = QtWidgets.QPushButton(self.inputBox)
        self.inputBrowse.setGeometry(QtCore.QRect(480, 10, 75, 23))
        self.inputBrowse.setObjectName("inputBrowse")
        self.inputLastFile = QtWidgets.QPushButton(self.inputBox)
        self.inputLastFile.setGeometry(QtCore.QRect(10, 40, 71, 23))
        self.inputLastFile.setObjectName("inputLastFile")
        self.outputBox = QtWidgets.QGroupBox(self.funcSelect)
        self.outputBox.setGeometry(QtCore.QRect(20, 90, 581, 91))
        self.outputBox.setMinimumSize(QtCore.QSize(580, 91))
        self.outputBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputBox.setStyleSheet("/*QGroupBox { border: 1px}*/")
        self.outputBox.setTitle("")
        self.outputBox.setObjectName("outputBox")
        self.outputText = QtWidgets.QLabel(self.outputBox)
        self.outputText.setGeometry(QtCore.QRect(10, 12, 81, 20))
        self.outputText.setObjectName("outputText")
        self.outputPath = QtWidgets.QLineEdit(self.outputBox)
        self.outputPath.setGeometry(QtCore.QRect(90, 12, 371, 20))
        self.outputPath.setObjectName("outputPath")
        self.outputBrowse = QtWidgets.QPushButton(self.outputBox)
        self.outputBrowse.setGeometry(QtCore.QRect(480, 10, 75, 23))
        self.outputBrowse.setObjectName("outputBrowse")
        self.uploadStreamable = QtWidgets.QPushButton(self.outputBox)
        self.uploadStreamable.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.uploadStreamable.setStyleSheet("font-size:12px")
        self.uploadStreamable.setObjectName("uploadStreamable")
        self.uploadGfycat = QtWidgets.QPushButton(self.outputBox)
        self.uploadGfycat.setGeometry(QtCore.QRect(210, 50, 171, 31))
        self.uploadGfycat.setStyleSheet("font-size:12px")
        self.uploadGfycat.setObjectName("uploadGfycat")
        self.ccBox = QtWidgets.QGroupBox(self.funcSelect)
        self.ccBox.setGeometry(QtCore.QRect(20, 190, 581, 81))
        self.ccBox.setMinimumSize(QtCore.QSize(581, 81))
        self.ccBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ccBox.setFlat(False)
        self.ccBox.setCheckable(False)
        self.ccBox.setObjectName("ccBox")
        self.lutText = QtWidgets.QLabel(self.ccBox)
        self.lutText.setGeometry(QtCore.QRect(10, 23, 81, 16))
        self.lutText.setObjectName("lutText")
        self.lutPath = QtWidgets.QLineEdit(self.ccBox)
        self.lutPath.setGeometry(QtCore.QRect(90, 22, 381, 20))
        self.lutPath.setObjectName("lutPath")
        self.lutBrowse = QtWidgets.QPushButton(self.ccBox)
        self.lutBrowse.setGeometry(QtCore.QRect(480, 20, 75, 23))
        self.lutBrowse.setObjectName("lutBrowse")
        self.lutApply = QtWidgets.QPushButton(self.ccBox)
        self.lutApply.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.lutApply.setObjectName("lutApply")
        self.lutPreview = QtWidgets.QPushButton(self.ccBox)
        self.lutPreview.setGeometry(QtCore.QRect(90, 50, 75, 23))
        self.lutPreview.setObjectName("lutPreview")
        self.codecBox = QtWidgets.QGroupBox(self.funcSelect)
        self.codecBox.setGeometry(QtCore.QRect(20, 280, 581, 191))
        self.codecBox.setMinimumSize(QtCore.QSize(581, 161))
        self.codecBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.codecBox.setAutoFillBackground(False)
        self.codecBox.setStyleSheet("QSpinBox {\n"
"color:#fff;\n"
"border:1px solid rgb(100,100,100);\n"
"}\n"
"QComboBox {\n"
"color:#fff;\n"
"border:1px solid rgb(100,100,100);\n"
"font-size:10px;\n"
"}\n"
"QTabBar::tab {\n"
"    border: 1px solid rgb(100,100,100);\n"
"    color:#fff;\n"
"    padding: 4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #fff;\n"
"    color: #000;\n"
"}\n"
"")
        self.codecBox.setObjectName("codecBox")
        self.vCodecLabel = QtWidgets.QLabel(self.codecBox)
        self.vCodecLabel.setGeometry(QtCore.QRect(10, 23, 81, 16))
        self.vCodecLabel.setObjectName("vCodecLabel")
        self.vCodecDrop = QtWidgets.QComboBox(self.codecBox)
        self.vCodecDrop.setGeometry(QtCore.QRect(100, 20, 131, 22))
        self.vCodecDrop.setStyleSheet("color:#fff;border:1px solid  rgb(100,100,100)")
        self.vCodecDrop.setObjectName("vCodecDrop")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.vCodecDrop.addItem("")
        self.aCodecLabel = QtWidgets.QLabel(self.codecBox)
        self.aCodecLabel.setGeometry(QtCore.QRect(340, 23, 81, 16))
        self.aCodecLabel.setObjectName("aCodecLabel")
        self.aCodecDrop = QtWidgets.QComboBox(self.codecBox)
        self.aCodecDrop.setGeometry(QtCore.QRect(420, 20, 69, 22))
        self.aCodecDrop.setStyleSheet("color:#fff;border:1px solid  rgb(100,100,100)")
        self.aCodecDrop.setObjectName("aCodecDrop")
        self.aCodecDrop.addItem("")
        self.aCodecDrop.addItem("")
        self.aCodecDrop.addItem("")
        self.aCodecDrop.addItem("")
        self.vCodecTabs = QtWidgets.QTabWidget(self.codecBox)
        self.vCodecTabs.setGeometry(QtCore.QRect(10, 50, 321, 101))
        self.vCodecTabs.setStyleSheet("")
        self.vCodecTabs.setObjectName("vCodecTabs")
        self.x264Tab = QtWidgets.QWidget()
        self.x264Tab.setAutoFillBackground(False)
        self.x264Tab.setStyleSheet("")
        self.x264Tab.setObjectName("x264Tab")
        self.x264QLabel = QtWidgets.QLabel(self.x264Tab)
        self.x264QLabel.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.x264QLabel.setObjectName("x264QLabel")
        self.x264PLabel = QtWidgets.QLabel(self.x264Tab)
        self.x264PLabel.setGeometry(QtCore.QRect(10, 44, 47, 13))
        self.x264PLabel.setObjectName("x264PLabel")
        self.x264Preset = QtWidgets.QComboBox(self.x264Tab)
        self.x264Preset.setGeometry(QtCore.QRect(70, 40, 121, 22))
        self.x264Preset.setStyleSheet("color:#fff")
        self.x264Preset.setObjectName("x264Preset")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Preset.addItem("")
        self.x264Var_2 = QtWidgets.QSlider(self.x264Tab)
        self.x264Var_2.setGeometry(QtCore.QRect(80, 10, 101, 16))
        self.x264Var_2.setStyleSheet("QSlider::handle {background-color:rgb(100,100,100)} {border:0px solid black}")
        self.x264Var_2.setMaximum(51)
        self.x264Var_2.setSliderPosition(23)
        self.x264Var_2.setOrientation(QtCore.Qt.Horizontal)
        self.x264Var_2.setObjectName("x264Var_2")
        self.x264VarLabel = QtWidgets.QLabel(self.x264Tab)
        self.x264VarLabel.setGeometry(QtCore.QRect(50, 10, 47, 13))
        self.x264VarLabel.setObjectName("x264VarLabel")
        self.x264QLabel.raise_()
        self.x264PLabel.raise_()
        self.x264Preset.raise_()
        self.x264VarLabel.raise_()
        self.x264Var_2.raise_()
        self.vCodecTabs.addTab(self.x264Tab, "")
        self.VP8Tab = QtWidgets.QWidget()
        self.VP8Tab.setAutoFillBackground(False)
        self.VP8Tab.setObjectName("VP8Tab")
        self.VP8Label = QtWidgets.QLabel(self.VP8Tab)
        self.VP8Label.setGeometry(QtCore.QRect(10, 14, 47, 16))
        self.VP8Label.setObjectName("VP8Label")
        self.VP8Var = QtWidgets.QSpinBox(self.VP8Tab)
        self.VP8Var.setGeometry(QtCore.QRect(80, 10, 51, 22))
        self.VP8Var.setStyleSheet("")
        self.VP8Var.setMinimum(100)
        self.VP8Var.setMaximum(20000)
        self.VP8Var.setSingleStep(100)
        self.VP8Var.setProperty("value", 3000)
        self.VP8Var.setObjectName("VP8Var")
        self.VP8Unit = QtWidgets.QLabel(self.VP8Tab)
        self.VP8Unit.setGeometry(QtCore.QRect(140, 14, 47, 13))
        self.VP8Unit.setObjectName("VP8Unit")
        self.vCodecTabs.addTab(self.VP8Tab, "")
        self.XvidTab = QtWidgets.QWidget()
        self.XvidTab.setAutoFillBackground(False)
        self.XvidTab.setObjectName("XvidTab")
        self.XvidLabel = QtWidgets.QLabel(self.XvidTab)
        self.XvidLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.XvidLabel.setObjectName("XvidLabel")
        self.XvidText = QtWidgets.QLabel(self.XvidTab)
        self.XvidText.setGeometry(QtCore.QRect(70, 40, 111, 16))
        self.XvidText.setObjectName("XvidText")
        self.XvidText2 = QtWidgets.QLabel(self.XvidTab)
        self.XvidText2.setGeometry(QtCore.QRect(190, 40, 101, 16))
        self.XvidText2.setObjectName("XvidText2")
        self.XvidVar = QtWidgets.QSlider(self.XvidTab)
        self.XvidVar.setGeometry(QtCore.QRect(120, 12, 101, 16))
        self.XvidVar.setStyleSheet("QSlider::handle {background-color: rgb(100,100,100)} {border:0px solid black}")
        self.XvidVar.setMinimum(1)
        self.XvidVar.setMaximum(31)
        self.XvidVar.setProperty("value", 10)
        self.XvidVar.setSliderPosition(10)
        self.XvidVar.setOrientation(QtCore.Qt.Horizontal)
        self.XvidVar.setObjectName("XvidVar")
        self.XvidVarLabel = QtWidgets.QLabel(self.XvidTab)
        self.XvidVarLabel.setGeometry(QtCore.QRect(90, 12, 47, 13))
        self.XvidVarLabel.setObjectName("XvidVarLabel")
        self.XvidLabel.raise_()
        self.XvidText.raise_()
        self.XvidText2.raise_()
        self.XvidVarLabel.raise_()
        self.XvidVar.raise_()
        self.vCodecTabs.addTab(self.XvidTab, "")
        self.NVENCTab = QtWidgets.QWidget()
        self.NVENCTab.setAutoFillBackground(False)
        self.NVENCTab.setObjectName("NVENCTab")
        self.NVENCPresets = QtWidgets.QComboBox(self.NVENCTab)
        self.NVENCPresets.setGeometry(QtCore.QRect(90, 10, 191, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.NVENCPresets.setFont(font)
        self.NVENCPresets.setStyleSheet("color:#fff; font-size: 9px;")
        self.NVENCPresets.setObjectName("NVENCPresets")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPresets.addItem("")
        self.NVENCPLabel = QtWidgets.QLabel(self.NVENCTab)
        self.NVENCPLabel.setGeometry(QtCore.QRect(30, 14, 47, 13))
        self.NVENCPLabel.setObjectName("NVENCPLabel")
        self.NVENCBLabel = QtWidgets.QLabel(self.NVENCTab)
        self.NVENCBLabel.setGeometry(QtCore.QRect(30, 44, 47, 13))
        self.NVENCBLabel.setObjectName("NVENCBLabel")
        self.NVENCVar = QtWidgets.QSpinBox(self.NVENCTab)
        self.NVENCVar.setGeometry(QtCore.QRect(90, 40, 61, 22))
        self.NVENCVar.setStyleSheet("")
        self.NVENCVar.setMinimum(100)
        self.NVENCVar.setMaximum(50000)
        self.NVENCVar.setSingleStep(100)
        self.NVENCVar.setProperty("value", 3000)
        self.NVENCVar.setDisplayIntegerBase(10)
        self.NVENCVar.setObjectName("NVENCVar")
        self.NVENCUnit = QtWidgets.QLabel(self.NVENCTab)
        self.NVENCUnit.setGeometry(QtCore.QRect(160, 44, 47, 13))
        self.NVENCUnit.setObjectName("NVENCUnit")
        self.vCodecTabs.addTab(self.NVENCTab, "")
        self.aCodecTabs = QtWidgets.QTabWidget(self.codecBox)
        self.aCodecTabs.setGeometry(QtCore.QRect(340, 50, 231, 101))
        self.aCodecTabs.setStyleSheet("")
        self.aCodecTabs.setObjectName("aCodecTabs")
        self.AACTab = QtWidgets.QWidget()
        self.AACTab.setAutoFillBackground(False)
        self.AACTab.setStyleSheet("")
        self.AACTab.setObjectName("AACTab")
        self.AACBitrateLabel = QtWidgets.QLabel(self.AACTab)
        self.AACBitrateLabel.setGeometry(QtCore.QRect(10, 13, 47, 13))
        self.AACBitrateLabel.setObjectName("AACBitrateLabel")
        self.AACBitrateVar = QtWidgets.QSpinBox(self.AACTab)
        self.AACBitrateVar.setGeometry(QtCore.QRect(100, 10, 42, 22))
        self.AACBitrateVar.setMinimum(32)
        self.AACBitrateVar.setMaximum(512)
        self.AACBitrateVar.setSingleStep(32)
        self.AACBitrateVar.setProperty("value", 128)
        self.AACBitrateVar.setObjectName("AACBitrateVar")
        self.AACBitrateUnit = QtWidgets.QLabel(self.AACTab)
        self.AACBitrateUnit.setGeometry(QtCore.QRect(150, 14, 47, 13))
        self.AACBitrateUnit.setObjectName("AACBitrateUnit")
        self.aCodecTabs.addTab(self.AACTab, "")
        self.vorbisTab = QtWidgets.QWidget()
        self.vorbisTab.setAutoFillBackground(False)
        self.vorbisTab.setObjectName("vorbisTab")
        self.vorbisLabel = QtWidgets.QLabel(self.vorbisTab)
        self.vorbisLabel.setGeometry(QtCore.QRect(10, 11, 81, 16))
        self.vorbisLabel.setObjectName("vorbisLabel")
        self.vorbisText = QtWidgets.QLabel(self.vorbisTab)
        self.vorbisText.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.vorbisText.setObjectName("vorbisText")
        self.vorbisVar = QtWidgets.QSlider(self.vorbisTab)
        self.vorbisVar.setGeometry(QtCore.QRect(110, 10, 81, 20))
        self.vorbisVar.setStyleSheet("QSlider::handle {background-color: rgb(100,100,100)} {border:0px solid black}")
        self.vorbisVar.setMinimum(0)
        self.vorbisVar.setMaximum(10)
        self.vorbisVar.setProperty("value", 3)
        self.vorbisVar.setSliderPosition(3)
        self.vorbisVar.setOrientation(QtCore.Qt.Horizontal)
        self.vorbisVar.setObjectName("vorbisVar")
        self.vorbisVarLabel = QtWidgets.QLabel(self.vorbisTab)
        self.vorbisVarLabel.setGeometry(QtCore.QRect(90, 12, 47, 13))
        self.vorbisVarLabel.setObjectName("vorbisVarLabel")
        self.vorbisLabel.raise_()
        self.vorbisText.raise_()
        self.vorbisVarLabel.raise_()
        self.vorbisVar.raise_()
        self.aCodecTabs.addTab(self.vorbisTab, "")
        self.MP3Tab = QtWidgets.QWidget()
        self.MP3Tab.setAutoFillBackground(False)
        self.MP3Tab.setObjectName("MP3Tab")
        self.MP3Label = QtWidgets.QLabel(self.MP3Tab)
        self.MP3Label.setGeometry(QtCore.QRect(10, 12, 47, 13))
        self.MP3Label.setObjectName("MP3Label")
        self.MP3Text = QtWidgets.QLabel(self.MP3Tab)
        self.MP3Text.setGeometry(QtCore.QRect(10, 40, 191, 16))
        self.MP3Text.setObjectName("MP3Text")
        self.MP3Var = QtWidgets.QSlider(self.MP3Tab)
        self.MP3Var.setGeometry(QtCore.QRect(110, 10, 81, 20))
        self.MP3Var.setStyleSheet("QSlider::handle {background-color:rgb(100,100,100)} {border:0px solid black}")
        self.MP3Var.setMinimum(1)
        self.MP3Var.setMaximum(9)
        self.MP3Var.setProperty("value", 3)
        self.MP3Var.setSliderPosition(3)
        self.MP3Var.setOrientation(QtCore.Qt.Horizontal)
        self.MP3Var.setObjectName("MP3Var")
        self.MP3VarLabel = QtWidgets.QLabel(self.MP3Tab)
        self.MP3VarLabel.setGeometry(QtCore.QRect(90, 12, 47, 13))
        self.MP3VarLabel.setObjectName("MP3VarLabel")
        self.MP3Label.raise_()
        self.MP3Text.raise_()
        self.MP3VarLabel.raise_()
        self.MP3Var.raise_()
        self.aCodecTabs.addTab(self.MP3Tab, "")
        self.changeFormat = QtWidgets.QPushButton(self.codecBox)
        self.changeFormat.setGeometry(QtCore.QRect(10, 160, 111, 23))
        self.changeFormat.setObjectName("changeFormat")
        self.label = QtWidgets.QLabel(self.codecBox)
        self.label.setGeometry(QtCore.QRect(130, 164, 391, 16))
        self.label.setObjectName("label")
        self.speedBox = QtWidgets.QGroupBox(self.funcSelect)
        self.speedBox.setGeometry(QtCore.QRect(20, 480, 171, 111))
        self.speedBox.setMinimumSize(QtCore.QSize(171, 111))
        self.speedBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.speedBox.setObjectName("speedBox")
        self.speedText = QtWidgets.QLabel(self.speedBox)
        self.speedText.setGeometry(QtCore.QRect(10, 33, 41, 16))
        self.speedText.setObjectName("speedText")
        self.speedPercent = QtWidgets.QLabel(self.speedBox)
        self.speedPercent.setGeometry(QtCore.QRect(110, 31, 16, 21))
        self.speedPercent.setStyleSheet("font-size:13px")
        self.speedPercent.setObjectName("speedPercent")
        self.speedApply = QtWidgets.QPushButton(self.speedBox)
        self.speedApply.setGeometry(QtCore.QRect(10, 80, 51, 23))
        self.speedApply.setObjectName("speedApply")
        self.speedVar = QtWidgets.QSpinBox(self.speedBox)
        self.speedVar.setGeometry(QtCore.QRect(60, 30, 42, 22))
        self.speedVar.setStyleSheet("color:#fff;border:1px solid rgb(100,100,100)")
        self.speedVar.setMinimum(1)
        self.speedVar.setMaximum(500)
        self.speedVar.setProperty("value", 100)
        self.speedVar.setObjectName("speedVar")
        self.speedPreview = QtWidgets.QPushButton(self.speedBox)
        self.speedPreview.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.speedPreview.setObjectName("speedPreview")
        self.extractBox = QtWidgets.QGroupBox(self.funcSelect)
        self.extractBox.setGeometry(QtCore.QRect(210, 480, 191, 111))
        self.extractBox.setMinimumSize(QtCore.QSize(171, 111))
        self.extractBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.extractBox.setObjectName("extractBox")
        self.extractStartText = QtWidgets.QLabel(self.extractBox)
        self.extractStartText.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.extractStartText.setObjectName("extractStartText")
        self.extractEndText = QtWidgets.QLabel(self.extractBox)
        self.extractEndText.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.extractEndText.setObjectName("extractEndText")
        self.extractStartSec = QtWidgets.QLabel(self.extractBox)
        self.extractStartSec.setGeometry(QtCore.QRect(170, 24, 16, 16))
        self.extractStartSec.setObjectName("extractStartSec")
        self.extractEndSec = QtWidgets.QLabel(self.extractBox)
        self.extractEndSec.setGeometry(QtCore.QRect(170, 54, 16, 16))
        self.extractEndSec.setObjectName("extractEndSec")
        self.extractApply = QtWidgets.QPushButton(self.extractBox)
        self.extractApply.setGeometry(QtCore.QRect(10, 79, 75, 23))
        self.extractApply.setObjectName("extractApply")
        self.extractPreview = QtWidgets.QPushButton(self.extractBox)
        self.extractPreview.setGeometry(QtCore.QRect(90, 79, 75, 23))
        self.extractPreview.setObjectName("extractPreview")
        self.extractStartSec_2 = QtWidgets.QLabel(self.extractBox)
        self.extractStartSec_2.setGeometry(QtCore.QRect(116, 24, 16, 16))
        self.extractStartSec_2.setObjectName("extractStartSec_2")
        self.extractStartSec_3 = QtWidgets.QLabel(self.extractBox)
        self.extractStartSec_3.setGeometry(QtCore.QRect(116, 54, 16, 16))
        self.extractStartSec_3.setObjectName("extractStartSec_3")
        self.extractStartSecVar = QtWidgets.QSpinBox(self.extractBox)
        self.extractStartSecVar.setGeometry(QtCore.QRect(131, 20, 36, 22))
        self.extractStartSecVar.setStyleSheet("color:#fff;border:1px solid rgb(100,100,100)")
        self.extractStartSecVar.setMaximum(59)
        self.extractStartSecVar.setObjectName("extractStartSecVar")
        self.extractEndSecVar = QtWidgets.QSpinBox(self.extractBox)
        self.extractEndSecVar.setGeometry(QtCore.QRect(131, 49, 36, 22))
        self.extractEndSecVar.setStyleSheet("color:#fff;border:1px solid rgb(100,100,100)")
        self.extractEndSecVar.setMaximum(59)
        self.extractEndSecVar.setObjectName("extractEndSecVar")
        self.extractStartMinVar = QtWidgets.QSpinBox(self.extractBox)
        self.extractStartMinVar.setGeometry(QtCore.QRect(70, 20, 42, 22))
        self.extractStartMinVar.setStyleSheet("color:#fff;border:1px solid rgb(100,100,100)")
        self.extractStartMinVar.setMaximum(16777215)
        self.extractStartMinVar.setObjectName("extractStartMinVar")
        self.extractEndMinVar = QtWidgets.QSpinBox(self.extractBox)
        self.extractEndMinVar.setGeometry(QtCore.QRect(70, 50, 42, 22))
        self.extractEndMinVar.setStyleSheet("color:#fff;border:1px solid rgb(100,100,100)")
        self.extractEndMinVar.setMaximum(16777215)
        self.extractEndMinVar.setObjectName("extractEndMinVar")
        self.cropBox = QtWidgets.QGroupBox(self.funcSelect)
        self.cropBox.setGeometry(QtCore.QRect(420, 480, 181, 111))
        self.cropBox.setMinimumSize(QtCore.QSize(171, 111))
        self.cropBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cropBox.setObjectName("cropBox")
        self.cropWidthText = QtWidgets.QLabel(self.cropBox)
        self.cropWidthText.setGeometry(QtCore.QRect(10, 21, 71, 16))
        self.cropWidthText.setObjectName("cropWidthText")
        self.cropHeightText = QtWidgets.QLabel(self.cropBox)
        self.cropHeightText.setGeometry(QtCore.QRect(10, 51, 71, 16))
        self.cropHeightText.setObjectName("cropHeightText")
        self.cropWidthVar = QtWidgets.QLineEdit(self.cropBox)
        self.cropWidthVar.setGeometry(QtCore.QRect(90, 20, 41, 20))
        self.cropWidthVar.setObjectName("cropWidthVar")
        self.cropHeightVar = QtWidgets.QLineEdit(self.cropBox)
        self.cropHeightVar.setGeometry(QtCore.QRect(90, 50, 41, 20))
        self.cropHeightVar.setObjectName("cropHeightVar")
        self.cropWidthPx = QtWidgets.QLabel(self.cropBox)
        self.cropWidthPx.setGeometry(QtCore.QRect(135, 24, 16, 16))
        self.cropWidthPx.setObjectName("cropWidthPx")
        self.cropHeightPx = QtWidgets.QLabel(self.cropBox)
        self.cropHeightPx.setGeometry(QtCore.QRect(135, 54, 16, 16))
        self.cropHeightPx.setObjectName("cropHeightPx")
        self.cropApply = QtWidgets.QPushButton(self.cropBox)
        self.cropApply.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.cropApply.setObjectName("cropApply")
        self.cropPreview = QtWidgets.QPushButton(self.cropBox)
        self.cropPreview.setGeometry(QtCore.QRect(90, 80, 75, 23))
        self.cropPreview.setObjectName("cropPreview")
        self.convertMp3 = QtWidgets.QPushButton(self.funcSelect)
        self.convertMp3.setGeometry(QtCore.QRect(20, 600, 91, 61))
        self.convertMp3.setMinimumSize(QtCore.QSize(91, 61))
        self.convertMp3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.convertMp3.setStyleSheet("font-size:16px")
        self.convertMp3.setObjectName("convertMp3")
        self.saveAsGif = QtWidgets.QPushButton(self.funcSelect)
        self.saveAsGif.setGeometry(QtCore.QRect(120, 600, 91, 61))
        self.saveAsGif.setMinimumSize(QtCore.QSize(91, 61))
        self.saveAsGif.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.saveAsGif.setStyleSheet("font-size:16px")
        self.saveAsGif.setObjectName("saveAsGif")
        self.stabilizeVideo = QtWidgets.QPushButton(self.funcSelect)
        self.stabilizeVideo.setGeometry(QtCore.QRect(220, 600, 91, 61))
        self.stabilizeVideo.setMinimumSize(QtCore.QSize(91, 61))
        self.stabilizeVideo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stabilizeVideo.setStyleSheet("font-size:16px")
        self.stabilizeVideo.setObjectName("stabilizeVideo")
        self.label_3 = QtWidgets.QLabel(self.funcSelect)
        self.label_3.setGeometry(QtCore.QRect(360, 600, 191, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(191, 61))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setStyleSheet("background-image:url(logo.png)")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.customCommands = QtWidgets.QGroupBox(self.funcSelect)
        self.customCommands.setGeometry(QtCore.QRect(20, 670, 581, 91))
        self.customCommands.setStyleSheet("QGroupBox{border:1px solid rgb(100,100,100)}")
        self.customCommands.setObjectName("customCommands")
        self.customText = QtWidgets.QTextEdit(self.customCommands)
        self.customText.setGeometry(QtCore.QRect(10, 20, 481, 61))
        self.customText.setStyleSheet("border:1px solid rgb(100,100,100);; color:#fff;")
        self.customText.setObjectName("customText")
        self.customApply = QtWidgets.QPushButton(self.customCommands)
        self.customApply.setGeometry(QtCore.QRect(500, 20, 75, 23))
        self.customApply.setObjectName("customApply")
        self.outputBox.raise_()
        self.speedBox.raise_()
        self.extractBox.raise_()
        self.cropBox.raise_()
        self.stabilizeVideo.raise_()
        self.convertMp3.raise_()
        self.inputBox.raise_()
        self.saveAsGif.raise_()
        self.label_3.raise_()
        self.ccBox.raise_()
        self.codecBox.raise_()
        self.customCommands.raise_()
        self.editMenu.addWidget(self.funcSelect)

        self.retranslateUi(GEditorUI)
        self.editMenu.setCurrentIndex(0)
        self.vCodecTabs.setCurrentIndex(0)
        self.x264Preset.setCurrentIndex(0)
        self.aCodecTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GEditorUI)

    def retranslateUi(self, GEditorUI):
        _translate = QtCore.QCoreApplication.translate
        GEditorUI.setWindowTitle(_translate("GEditorUI", "Form"))
        self.welcome_text.setText(_translate("GEditorUI", "WELCOME TO"))
        self.button_menu_next.setText(_translate("GEditorUI", "Next"))
        self.inputText.setText(_translate("GEditorUI", "Import:"))
        self.inputBrowse.setText(_translate("GEditorUI", "Browse.."))
        self.inputLastFile.setText(_translate("GEditorUI", "Use Last"))
        self.outputText.setText(_translate("GEditorUI", "Output path: "))
        self.outputBrowse.setText(_translate("GEditorUI", "Browse.."))
        self.uploadStreamable.setText(_translate("GEditorUI", "Upload to Streamable"))
        self.uploadGfycat.setText(_translate("GEditorUI", "Upload to Gfycat"))
        self.ccBox.setTitle(_translate("GEditorUI", "Color Correction"))
        self.lutText.setText(_translate("GEditorUI", "Choose LUT:"))
        self.lutBrowse.setText(_translate("GEditorUI", "Browse.."))
        self.lutApply.setText(_translate("GEditorUI", "Apply"))
        self.lutPreview.setText(_translate("GEditorUI", "Preview"))
        self.codecBox.setTitle(_translate("GEditorUI", "Codecs"))
        self.vCodecLabel.setText(_translate("GEditorUI", "Video Codec: "))
        self.vCodecDrop.setItemText(0, _translate("GEditorUI", "default"))
        self.vCodecDrop.setItemText(1, _translate("GEditorUI", "x264 (mp4) (optimal)"))
        self.vCodecDrop.setItemText(2, _translate("GEditorUI", "VP8 (webm)"))
        self.vCodecDrop.setItemText(3, _translate("GEditorUI", "Xvid (avi)"))
        self.vCodecDrop.setItemText(4, _translate("GEditorUI", "x265 (mp4)"))
        self.vCodecDrop.setItemText(5, _translate("GEditorUI", "H.264 NVENC (mp4)"))
        self.vCodecDrop.setItemText(6, _translate("GEditorUI", "HEVC NVENC (mp4)"))
        self.aCodecLabel.setText(_translate("GEditorUI", "Audio codec:"))
        self.aCodecDrop.setItemText(0, _translate("GEditorUI", "default"))
        self.aCodecDrop.setItemText(1, _translate("GEditorUI", "AAC"))
        self.aCodecDrop.setItemText(2, _translate("GEditorUI", "Vorbis"))
        self.aCodecDrop.setItemText(3, _translate("GEditorUI", "MP3"))
        self.x264QLabel.setText(_translate("GEditorUI", "CRF: "))
        self.x264PLabel.setText(_translate("GEditorUI", "Preset:"))
        self.x264Preset.setCurrentText(_translate("GEditorUI", "ultrafast"))
        self.x264Preset.setItemText(0, _translate("GEditorUI", "ultrafast"))
        self.x264Preset.setItemText(1, _translate("GEditorUI", "superfast"))
        self.x264Preset.setItemText(2, _translate("GEditorUI", "veryfast"))
        self.x264Preset.setItemText(3, _translate("GEditorUI", "faster"))
        self.x264Preset.setItemText(4, _translate("GEditorUI", "fast"))
        self.x264Preset.setItemText(5, _translate("GEditorUI", "medium (Default)"))
        self.x264Preset.setItemText(6, _translate("GEditorUI", "slow"))
        self.x264Preset.setItemText(7, _translate("GEditorUI", "slower"))
        self.x264Preset.setItemText(8, _translate("GEditorUI", "veryslow"))
        self.x264VarLabel.setText(_translate("GEditorUI", "23"))
        self.vCodecTabs.setTabText(self.vCodecTabs.indexOf(self.x264Tab), _translate("GEditorUI", "x264/x265"))
        self.VP8Label.setText(_translate("GEditorUI", "Bitrate: "))
        self.VP8Unit.setText(_translate("GEditorUI", "kbps"))
        self.vCodecTabs.setTabText(self.vCodecTabs.indexOf(self.VP8Tab), _translate("GEditorUI", "VP8"))
        self.XvidLabel.setText(_translate("GEditorUI", "Quality scale:"))
        self.XvidText.setText(_translate("GEditorUI", "1 - highest quality"))
        self.XvidText2.setText(_translate("GEditorUI", "31 - lowest quality"))
        self.XvidVarLabel.setText(_translate("GEditorUI", "10"))
        self.vCodecTabs.setTabText(self.vCodecTabs.indexOf(self.XvidTab), _translate("GEditorUI", "Xvid"))
        self.NVENCPresets.setItemText(0, _translate("GEditorUI", "default (Default)"))
        self.NVENCPresets.setItemText(1, _translate("GEditorUI", "slow (High quality 2 passes)"))
        self.NVENCPresets.setItemText(2, _translate("GEditorUI", "medium (High quality 1 pass)"))
        self.NVENCPresets.setItemText(3, _translate("GEditorUI", "fast (High performance 1 pass)"))
        self.NVENCPresets.setItemText(4, _translate("GEditorUI", "hp (High performance)"))
        self.NVENCPresets.setItemText(5, _translate("GEditorUI", "hq (High quality)"))
        self.NVENCPresets.setItemText(6, _translate("GEditorUI", "bd (Bluray disk)"))
        self.NVENCPresets.setItemText(7, _translate("GEditorUI", "ll (Low latency)"))
        self.NVENCPresets.setItemText(8, _translate("GEditorUI", "llhq (Low latency high quality)"))
        self.NVENCPresets.setItemText(9, _translate("GEditorUI", "llhp (Low latency high performance)"))
        self.NVENCPresets.setItemText(10, _translate("GEditorUI", "lossless (Lossless)"))
        self.NVENCPresets.setItemText(11, _translate("GEditorUI", "loslesshp (Lossless high performance)"))
        self.NVENCPLabel.setText(_translate("GEditorUI", "Preset: "))
        self.NVENCBLabel.setText(_translate("GEditorUI", "Bitrate: "))
        self.NVENCUnit.setText(_translate("GEditorUI", "kbps"))
        self.vCodecTabs.setTabText(self.vCodecTabs.indexOf(self.NVENCTab), _translate("GEditorUI", "NVENC"))
        self.AACBitrateLabel.setText(_translate("GEditorUI", "Bitrate:"))
        self.AACBitrateUnit.setText(_translate("GEditorUI", "kbps"))
        self.aCodecTabs.setTabText(self.aCodecTabs.indexOf(self.AACTab), _translate("GEditorUI", "AAC"))
        self.vorbisLabel.setText(_translate("GEditorUI", "Quality scale:"))
        self.vorbisText.setText(_translate("GEditorUI", "Higher - higher quality"))
        self.vorbisVarLabel.setText(_translate("GEditorUI", "3"))
        self.aCodecTabs.setTabText(self.aCodecTabs.indexOf(self.vorbisTab), _translate("GEditorUI", "Vorbis"))
        self.MP3Label.setText(_translate("GEditorUI", "Quality:"))
        self.MP3Text.setText(_translate("GEditorUI", "Lower - higher quality"))
        self.MP3VarLabel.setText(_translate("GEditorUI", "3"))
        self.aCodecTabs.setTabText(self.aCodecTabs.indexOf(self.MP3Tab), _translate("GEditorUI", "MP3"))
        self.changeFormat.setText(_translate("GEditorUI", "Change Codec"))
        self.label.setText(_translate("GEditorUI", "Choose output path after selecting codec."))
        self.speedBox.setTitle(_translate("GEditorUI", "Speed Controls"))
        self.speedText.setText(_translate("GEditorUI", "Speed:"))
        self.speedPercent.setText(_translate("GEditorUI", "%"))
        self.speedApply.setText(_translate("GEditorUI", "Go"))
        self.speedPreview.setText(_translate("GEditorUI", "Preview"))
        self.extractBox.setTitle(_translate("GEditorUI", "Extract Subclip"))
        self.extractStartText.setText(_translate("GEditorUI", "Start Time:"))
        self.extractEndText.setText(_translate("GEditorUI", "End time:"))
        self.extractStartSec.setText(_translate("GEditorUI", "s"))
        self.extractEndSec.setText(_translate("GEditorUI", "s"))
        self.extractApply.setText(_translate("GEditorUI", "Extract"))
        self.extractPreview.setText(_translate("GEditorUI", "Preview"))
        self.extractStartSec_2.setText(_translate("GEditorUI", "m"))
        self.extractStartSec_3.setText(_translate("GEditorUI", "m"))
        self.cropBox.setTitle(_translate("GEditorUI", "Crop Video"))
        self.cropWidthText.setText(_translate("GEditorUI", "Crop Width:"))
        self.cropHeightText.setText(_translate("GEditorUI", "Crop Height:"))
        self.cropWidthPx.setText(_translate("GEditorUI", "px"))
        self.cropHeightPx.setText(_translate("GEditorUI", "px"))
        self.cropApply.setText(_translate("GEditorUI", "Crop"))
        self.cropPreview.setText(_translate("GEditorUI", "Preview"))
        self.convertMp3.setText(_translate("GEditorUI", "Convert \n"
"to MP3"))
        self.saveAsGif.setText(_translate("GEditorUI", "Save as\n"
"GIF"))
        self.stabilizeVideo.setText(_translate("GEditorUI", "Stabilize\n"
"Video"))
        self.customCommands.setTitle(_translate("GEditorUI", "Custom Commands"))
        self.customText.setPlaceholderText(_translate("GEditorUI", "Warning: For advanced users. Enter a custom ffmpeg command to execute."))
        self.customApply.setText(_translate("GEditorUI", "Execute"))

import logg_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GEditorUI = QtWidgets.QWidget()
    ui = Ui_GEditorUI()
    ui.setupUi(GEditorUI)
    GEditorUI.show()
    sys.exit(app.exec_())

